### ISSUE TITLE
ERROR: Cannot install -r requirements.txt (line 7) and urllib3==1.25.1 because these package versions have conflicting dependencies.

### ISSUE THREAD

**Issue by RaccoonDML** [microsoft/oac-explore#23]
why conflict in reqirements.txt ?

**Comment by 201520906050** [comment]
me too

**Comment by RaccoonDML** [comment]
I make it by installing the packages one by one from a blank environment according to the error massage

**Comment by RaccoonDML** [comment]
More specifically! 
torch==1.1
ray[rllib,debug]==0.7.0
gitdb2==2.0.5
GitPython==2.1.11
gtimer==1.0.0b5
python-dateutil==2.7.5
git+git://github.com/openai/gym.git@f380a0e871ae7fa9593fb452433ee9055ddf02eb
tqdm==4.32.1
mujoco-py==2.0.2.5
numpy==1.16.4
