### ISSUE TITLE
disabling code signature checker

### ISSUE THREAD

**Issue by samuelstanton** [microsoft/oac-explore#4]
I've forked the repo and started making some changes to try something out, but the code appears to have a signature checker, because when I try to run `main.py` the only output I get is the git diff and then the code exits. Any suggestions on how to disable that? 

Obviously I have verified that I can run `main.py` locally on the master branch, the issue is on my custom branch.

**Comment by quanvuong** [comment]
Hi Samuel,

I suggested commenting out the following if statement

https://github.com/microsoft/oac-explore/blob/715db5a2f0b8fead865fafc522d5820d477a7ed3/launcher_util.py#L137
