### ISSUE TITLE
Seed 3 is omitted in plot_against_baseline.py?

### ISSUE THREAD

**Issue by seann999** [microsoft/oac-explore#5]
https://github.com/microsoft/oac-explore/blob/715db5a2f0b8fead865fafc522d5820d477a7ed3/plotting/plot_against_baseline.py#L130
Is there a reason seed 3 is omitted?

**Comment by quanvuong** [comment]
Oh this was only for debugging. One of the run on my local computer fails because the machine ran out of memory and I was trying to figure out which one it was. 

I have updated the code to include the result for seed 3.
